### ISSUE TITLE
Incorrect profile info

### ISSUE THREAD

**Issue by cckole** [quintuslabs/GroceryStore#3]
### Proposals

Before I could use the app, I had to sign up, so I have a profile. But when I checked my profile after signing up and getting into the app, it was another information I was seeing. Normally in the menu, I saw ckole (my name) at the top, which is my profile, but when I accessed my profile, another info was found there.

### Expected behavior

I expected to see my profile information and not another’s. If I’m the original owner of the account, why another person’s info. That is not okay.

![Screenshot_20190704-005322](https://user-images.githubusercontent.com/36272218/60631304-c5f20900-9df6-11e9-86ed-fdf45fbf2a68.png)

### Steps to reproduce
Launch the app
- sign up with your gmail and other informations
- After entering the app, click on the menu and click on my profile. You wi

**Comment by quintuslabs** [comment]
This is a templet. i m not using any server for storing data . so this is a static page. u can change according to your requirement
